---
- hosts: localhost
  gather_facts: False

  tasks:

   - name: Creating ec2 t2.micro
     ec2:
	     name: discord-remindbot
             key_name: example_AWSkeyname
             group: example_group
             instance_type: t2.micro
             image: free_tier_ami_ID
             region: ec2_region
             vpc_subnet_id: subnet_id
             wait: true
             count: 1
     register: ec2


# If ansible interpreter is not using python3
# ansible-playbook ec2_t2micro.yml -e 'ansible_python_interpreter=/usr/bin/python3'
